### PR TITLE
Hot water zone control

### PR DESCRIPTION
**Pull request by andersonshatch**
Add support for controlling a hot water zone.

### CODE REVIEW

**Comment by wmalgadey** [comment]
thank you for the changes

**Comment by wmalgadey** [comment]
@andersonshatch I think, I did the merge too fast ;)

I did some changes in (https://github.com/wmalgadey/PyTado/commit/5925c9f8b9e50648b8d9ad2bf0810c51bd4a98f3)

you have to use:
`setZoneOverlay(<<zone>>, <<overlayMode>>, None, None, deviceType='HOT_WATER', power="ON")`
or
`setZoneOverlay(<<zone>>, <<overlayMode>>, None, None, deviceType='HOT_WATER', power="OFF")`

**Comment by andersonshatch** [comment]
Looks good anyhow, thanks for incorporating it! 🎉

**Comment by andersonshatch** [comment]
Looks good anyhow, thanks for incorporating it! 🎉

**Pull request merged**
