### PR TITLE
Add Energy IQ Tariff and Meter Reading support

### LINKED ISSUE #59: IDEA: Add Gas usage
Is it be possible to add gas meter usage via the API? That would be a nice feature to automatically add gas usage when combined with DSMR / Home Assistant.

### PR DESCRIPTION
**Pull request by Coffee2CodeNL**
- Refactored `Tado._apiCall()` to support alternative EnergyIQ url
- Refactored `Tado._refresh_token()` and `Tado._loginV2()` to use proper `client_id` and `client_secret`, and updated `Referer` header
- Added `Tado.energyiq2url` pointing at the right endpoint for EIQ stuff
- Added `Tado.getEIQTariffs()` to get all submitted tariffs
- Added `Tado.getEIQMeterReadings()` to get all submitted meter readings
- Added `Tado.setEIQMeterReadings()` to set today's meter reading 
- Added `Tado.setEIQTariff()` to set current or a period's tariff

Issue #59 also discusses this, so, closes #59

### CODE REVIEW

**Comment by Coffee2CodeNL** [comment]
Closes #59

`Tado.setEIQMeterReadings()` and `Tado.setEIQTariff()` have been added and confirmed to be working

Could add functionality to edit/delete meter readings or tariffs, but don't see a reason to right now as you can do that from the UI.

**Comment by wmalgadey** [comment]
@Coffee2CodeNL 

> Refactored Tado._refresh_token() and Tado._loginV2() to use proper client_id and client_secret, and updated Referer header

You actually changed the client_id and _secret, do you have a ressource as to why we have to change it? Or should we maybe add a switch to decide which one to use?

**Comment by Coffee2CodeNL** [comment]
> @Coffee2CodeNL
> 
> > Refactored Tado._refresh_token() and Tado._loginV2() to use proper client_id and client_secret, and updated Referer header
> 
> You actually changed the client_id and _secret, do you have a ressource as to why we have to change it? Or should we maybe add a switch to decide which one to use?

The website (app.tado.com) uses those now.
It's necessary to authenticate with the Energy IQ endpoint.

**Comment by wmalgadey** [comment]
Ok, then let's try :D

**Comment by niro1987** [comment]
When can we expect this to be added to a release?

**Comment by wmalgadey** [comment]
done!

**Pull request merged**
