### PR TITLE
Added ability to get device info and set temperatureOffset Closes #39

### LINKED ISSUE #39: Unable to update temperatureOffset
Assume I need an issue for the PR to link to?

### PR DESCRIPTION
**Pull request by north3221**
added new device domain to make that possible but keep backwards compatibility
likely needs some further testing

### CODE REVIEW

**Comment by north3221** [comment]
Hey not sure of the best way to do a PR, my first ever one... likely not direct from my master branch, forgot to create a branch, doh!

Basically I want to be able to change the temp offset for a device and I'd like it in Home Assistant. Did some testing and found out how to do it, was gonna write direct in my HA to make it work but dug through the HA integration code seems it uses your tado interface lib, so I updated your lib and raised this PR. If you accept I'll do a PR to the HA integration to open it up

**Comment by north3221** [comment]
Hi, I appreciate I likely need to make a few changes for this to be accepted, but is anyone still maintaining this? Just want to check before I go any further down the road of trying to get a PR in.

Let me know and provide any feedback and can sort

**Comment by wmalgadey** [comment]
sorry for the late reply @north3221! I didn't recieve any notification, I have to change my github settings asap 😵

**Comment by north3221** [comment]
Ha no worries @wmalgadey, I have it working as just have my custom component overwriting the core one.

But yeah please take a look, and accept the pr if it's ok or let me know any changes needed.

Once done I'll raise a pr to core

**Pull request merged**
