### PR TITLE
Adding the Minder API

### PR DESCRIPTION
**Pull request by erwindouna**
A proposal to add the Minder API to get the running times. My Black linter made more changes than needed. Yet, I didn't found any guidelines or settings. Hope you like it! :)

### CODE REVIEW

**Comment by wmalgadey** [comment]
sadly me just made a major refactoring (https://github.com/wmalgadey/PyTado/pull/61). @Coffee2CodeNL what would you say?

**Comment by Coffee2CodeNL** [comment]
Yeah we could do that.

This MR does contain too many unrelated changes by the linter.

@erwindouna can you revert the linter changes?

**Comment by wmalgadey** [comment]
@erwindouna can you resolve the merge conflicts?

**Comment by wmalgadey** [comment]
transfered the changes to https://github.com/wmalgadey/PyTado/pull/107. Closing this PR!

**Pull request closed without merging**
