### PR TITLE
Changed authentication url from my.tado.com to auth.tado.com

### PR DESCRIPTION
**Pull request by p0thi**
This changes target the recent and critical changes tado made to their authentication process mentioned in chrism0dwk/PyTado#6 and #11 .
All my tests passed and it worked again.
It would be great if the changes could be published to https://pypi.org/project/python-tado/ ASAP too.

### CODE REVIEW

**Comment by JanC** [comment]
+1 
@wmalgadey could you merge and release please

**Comment by marcgarciamarti** [comment]
Thanks guys! how do I know when this fix will get to production?

**Comment by wmalgadey** [comment]
@marcgarciamarti you mean productive in where? Homeassistant?

**Comment by JanC** [comment]
I believe @marcgarciamarti is asking when will `PyTado` be published on https://pypi.org/project/python-tado/
.. which already happened.

**Pull request merged**
