### PR TITLE
Refactoring + New Functionality

### LINKED ISSUE #58: Mask access token
I think it might be a bad idea to write the full access token to the log (at the `Information` level). This library is used in the home assistant integration and outputs the following to the log ever x minutes (where I obviously replaced part of it by xxx):

```plain
2023-01-26 10:27:53.021 INFO (SyncWorker_13) [PyTado.interface] api call result: {"access_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdxxxx","token_type":"bearer","refresh_token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.xxxx","expires_in":599,"scope":"home.user","jti":"e1e7b208-9ffa-4127-a8e6-509351433ee2"}
```

I don't think the access and the refresh token should be in the logs at all, but if you think there is a good reason for, could you be so kind by doing that only in `debug` mode? Than you can opt-in to see them and the rest of the users get a little more secure.

It's just a matter of switching to `_LOGGER.debug(...)`

### PR DESCRIPTION
**Pull request by Coffee2CodeNL**
Futureproofing the way API calls work as well, making sure that it doesn't get messy

All in all, I'm cleaning this project up, get it up to PEP8 spec and see what else we can figure out with this

- Extracted the entire API code, stuck it in http.py
- Extracted the logging code, stuck it in logging.py
- Added a filter to the logger to wipe out sensitive information (tokens, passwords, etc) (Closes #58)
- Removed all debugCalls, instead used a hook to catch all requests and log them when debugging
- Changed the way the logs look, they're much more readable now
- Closes #53 because I added it
- Closes #51 because I added it
- Deprecating the entirety of the wrongly cased functions (but they still work, they just pass through to the proper ones)
- Added the constants to constants, but that's just legacy stuff now
- Added three new exceptions, more to come
- Proper use of f-strings, instead of old format format
- Variable import based on StrEnum availability, will import polyfills otherwise
- Added ReprEnum Polyfill
- Added StrEnum Polyfill
- Updated the tests to reflect the changes
- Moved some stuff around into their own subpackages
- Updated GitHub actions to test current version (3.11) as well.

### CODE REVIEW

**Comment by Coffee2CodeNL** [comment]
`Http.request()` is a behemoth at the moment, but I'll be pulling it apart into separate functions when I continue working on this

**Comment by Coffee2CodeNL** [comment]
Ready for review

**Comment by wmalgadey** [comment]
Wow, @Coffee2CodeNL, great work.

I did take a look into your changes, and they seem fine to me. Because of the quantity, I am not able to see if the mentioned problems are really solved and if new problems may arise.

  * Is anyone able to review this? @palazzem or @chrism0dwk maybe?
  * Why does we have to change the casing of the public API?

I do understand the reasons for the separation into http.py and logging.py, but the public API just adds a new layer of complexity.

Should we remove the other API someday (and when)? Maintaining two APIs seems a bit tedious, doesn't it?

**Comment by Coffee2CodeNL** [comment]
Hey @wmalgadey the wrongly cased API has a deprecation notice so I'd say keep it in for like, two more version bumps.

I did that because Python methods are supposed to be snake case instead of how they were currently written.

Also, #58 is in logging.py

#53 in http.py

and finally #51 is a new method in interface.py

**Pull request merged**
