### PR TITLE
Report swing mode in tado zone.

### PR DESCRIPTION
**Pull request by bdraco**
Tado added swing mode to the api.  This change adds reporting of swing mode
> 

> Here at tado° we try to optimize our products and to offer the best solution to our customers.
> At the moment we are investigating ways to improve and expand the capabilities of our tado° Smart AC Controller.
> For this we would like to test a new improved command set, which supports the swing function of your AC.
> If you are happy to help us improve the tado° Smart AC Controller please answer this email and we will update your device.
> 
> Thank you very much for your time.
> We look forward to your reply.
> 
> Kind regards,
> tado° Team

### CODE REVIEW

**Comment by bdraco** [comment]
Thank you @wmalgadey !

**Comment by bdraco** [comment]
> Thank you @wmalgadey !

Would you mind bumping the PyPi package?  I'm going to get this integrated into Home Assistant this week if possible

**Comment by wmalgadey** [comment]
@bdraco sorry, for my slow reaction. I did upload 0.7.0 to pypi now

**Comment by bdraco** [comment]
@wmalgadey Thank you.  I'll work on the Home Assistant PR today

**Pull request merged**
